-- DO NOT EDIT
-- Generated by Exporter
-- Version: 2.8.11
SkillsBusinessLogicConfig = {}

SkillsBusinessLogicConfig.datas = 
{
	{ ID = 1, ProfessionalLimit = 1, LevelLimit = 1, SkillsType = 0, SkillsShowType = 0, Level = 1, Precondition = 0, Condition = 0, GoldConsume = 0, PropsConsume = 0, SkillsId = 0 	},
	{ ID = 2, ProfessionalLimit = 1, LevelLimit = 5, SkillsType = 0, SkillsShowType = 0, Level = 0, Precondition = 0, Condition = 0, GoldConsume = 0, PropsConsume = 0, SkillsId = 0 	}
}


-- ID
SkillsBusinessLogicConfig._datas = {}
for _, rec in pairs(SkillsBusinessLogicConfig.datas) do
	SkillsBusinessLogicConfig._datas[rec.ID] = rec
end

function SkillsBusinessLogicConfig.getByID(ID)
	return SkillsBusinessLogicConfig._datas[ID]
end
