// Generated by tabtoy
// Version: 2.8.11
// DO NOT EDIT!!
using System.Collections.Generic;

namespace NasData
{
	
	

	// Defined in table: TalkConfig
	
	public partial class TalkConfig : tabtoy._BaseConfig
	{
	
		public tabtoy.Logger TableLogger = new tabtoy.Logger();
	
		
		/// <summary> 
		/// TalkConfig
		/// </summary>
		public List<TalkConfigDefine> Datas = new List<TalkConfigDefine>(); 
	
	
		#region Index code
	 	Dictionary<string, TalkConfigDefine> _ByID = new Dictionary<string, TalkConfigDefine>();
        public TalkConfigDefine GetByID(string ID, TalkConfigDefine def = default(TalkConfigDefine))
        {
            TalkConfigDefine ret;
            if ( _ByID.TryGetValue( ID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(TalkConfigDefine) )
			{
				TableLogger.ErrorLine("GetByID failed, ID: {0}", ID);
			}

            return def;
        }
		
	
		#endregion
		#region Deserialize code
		public override void Deserialize(System.IO.Stream stream)
        {
            Deserialize(this, stream);
        }
		
		public static void Deserialize( TalkConfig ins, System.IO.Stream stream )
        {
            tabtoy.DataReader reader = new tabtoy.DataReader(stream);
            if (!reader.ReadHeader())
            {
                throw new System.Exception(string.Format("Deserialize failed: {0}", ins.GetType()));
            }
            Deserialize(ins, reader);
        }
		static tabtoy.DeserializeHandler<TalkConfig> _TalkConfigDeserializeHandler;
		static tabtoy.DeserializeHandler<TalkConfig> TalkConfigDeserializeHandler
		{
			get
			{
				if (_TalkConfigDeserializeHandler == null )
				{
					_TalkConfigDeserializeHandler = new tabtoy.DeserializeHandler<TalkConfig>(Deserialize);
				}

				return _TalkConfigDeserializeHandler;
			}
		}
		public static void Deserialize( TalkConfig ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0xa0000:
                	{
						ins.Datas.Add( reader.ReadStruct<TalkConfigDefine>(TalkConfigDefineDeserializeHandler) );
                	}
                	break; 
                }
             } 

			
			// Build TalkConfig Index
			for( int i = 0;i< ins.Datas.Count;i++)
			{
				var element = ins.Datas[i];
				
				ins._ByID.Add(element.ID, element);
				
			}
			
		}
		public static void Deserialize( TalkConfigDefine ins, System.IO.Stream stream )
        {
            tabtoy.DataReader reader = new tabtoy.DataReader(stream);
            if (!reader.ReadHeader())
            {
                throw new System.Exception(string.Format("Deserialize failed: {0}", ins.GetType()));
            }
            Deserialize(ins, reader);
        }
		static tabtoy.DeserializeHandler<TalkConfigDefine> _TalkConfigDefineDeserializeHandler;
		static tabtoy.DeserializeHandler<TalkConfigDefine> TalkConfigDefineDeserializeHandler
		{
			get
			{
				if (_TalkConfigDefineDeserializeHandler == null )
				{
					_TalkConfigDefineDeserializeHandler = new tabtoy.DeserializeHandler<TalkConfigDefine>(Deserialize);
				}

				return _TalkConfigDefineDeserializeHandler;
			}
		}
		public static void Deserialize( TalkConfigDefine ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x60000:
                	{
						ins.ID = reader.ReadString();
                	}
                	break; 
                	case 0x10001:
                	{
						ins.Desc = reader.ReadInt32();
                	}
                	break; 
                	case 0x10002:
                	{
						ins.FixedTalk = reader.ReadInt32();
                	}
                	break; 
                	case 0x10003:
                	{
						ins.RandomTalk = reader.ReadInt32();
                	}
                	break; 
                }
             } 

			
		}
		#endregion
	

	} 

	// Defined in table: TalkConfigDefine
	[System.Serializable]
	public partial class TalkConfigDefine : tabtoy._BaseConfig
	{
	
		
		/// <summary> 
		/// 唯一ID（索引加MakeIndex:true）
		/// </summary>
		public string ID = ""; 
		
		/// <summary> 
		/// 说话类型
		///0 固定对话
		///1 随机对话
		/// </summary>
		public int Desc = 0; 
		
		/// <summary> 
		/// 固定对话组
		/// </summary>
		public int FixedTalk = 0; 
		
		/// <summary> 
		/// 随机对话组
		/// </summary>
		public int RandomTalk = 0; 
	
	

	} 

}
