-- DO NOT EDIT
-- Generated by Exporter
-- Version: 2.8.11
TalkConfig = {}

local _datas = 
{
	{ ID = "1", Desc = 0, FixedTalk = 0, RandomTalk = 0 	},
	{ ID = "2", Desc = 0, FixedTalk = 0, RandomTalk = 0 	},
	{ ID = "3", Desc = 0, FixedTalk = 0, RandomTalk = 0 	},
	{ ID = "4", Desc = 0, FixedTalk = 0, RandomTalk = 0 	},
	{ ID = "5", Desc = 0, FixedTalk = 0, RandomTalk = 0 	},
	{ ID = "6", Desc = 0, FixedTalk = 0, RandomTalk = 0 	}
}


-- ID
TalkConfig.datas = {}
for _, rec in pairs(_datas) do
	TalkConfig.datas[rec.ID] = rec
end

function TalkConfig.getByID(ID)
	return TalkConfig.datas[ID]
end
