-- DO NOT EDIT
-- Generated by Exporter
-- Version: 2.8.11
EffectConfig = {}

EffectConfig.datas = 
{
	{ ID = 1, Path = "Effect/eff_09/Prefab/eff_09_008", Time = 0 	}
}


-- ID
EffectConfig._datas = {}
for _, rec in pairs(EffectConfig.datas) do
	EffectConfig._datas[rec.ID] = rec
end

function EffectConfig.getByID(ID)
	return EffectConfig._datas[ID]
end
