// Generated by tabtoy
// Version: 2.8.11
// DO NOT EDIT!!
using System.Collections.Generic;

namespace NasData
{
	
	

	// Defined in table: EffectConfig
	
	public partial class EffectConfig : tabtoy._BaseConfig
	{
	
		public tabtoy.Logger TableLogger = new tabtoy.Logger();
	
		
		/// <summary> 
		/// EffectConfig
		/// </summary>
		public List<EffectConfigDefine> Datas = new List<EffectConfigDefine>(); 
	
	
		#region Index code
	 	Dictionary<int, EffectConfigDefine> _ByID = new Dictionary<int, EffectConfigDefine>();
        public EffectConfigDefine GetByID(int ID, EffectConfigDefine def = default(EffectConfigDefine))
        {
            EffectConfigDefine ret;
            if ( _ByID.TryGetValue( ID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(EffectConfigDefine) )
			{
				TableLogger.ErrorLine("GetByID failed, ID: {0}", ID);
			}

            return def;
        }
		
	
		#endregion
		#region Deserialize code
		public override void Deserialize(System.IO.Stream stream)
        {
            Deserialize(this, stream);
        }
		
		public static void Deserialize( EffectConfig ins, System.IO.Stream stream )
        {
            tabtoy.DataReader reader = new tabtoy.DataReader(stream);
            if (!reader.ReadHeader())
            {
                throw new System.Exception(string.Format("Deserialize failed: {0}", ins.GetType()));
            }
            Deserialize(ins, reader);
        }
		static tabtoy.DeserializeHandler<EffectConfig> _EffectConfigDeserializeHandler;
		static tabtoy.DeserializeHandler<EffectConfig> EffectConfigDeserializeHandler
		{
			get
			{
				if (_EffectConfigDeserializeHandler == null )
				{
					_EffectConfigDeserializeHandler = new tabtoy.DeserializeHandler<EffectConfig>(Deserialize);
				}

				return _EffectConfigDeserializeHandler;
			}
		}
		public static void Deserialize( EffectConfig ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0xa0000:
                	{
						ins.Datas.Add( reader.ReadStruct<EffectConfigDefine>(EffectConfigDefineDeserializeHandler) );
                	}
                	break; 
                }
             } 

			
			// Build EffectConfig Index
			for( int i = 0;i< ins.Datas.Count;i++)
			{
				var element = ins.Datas[i];
				
				ins._ByID.Add(element.ID, element);
				
			}
			
		}
		public static void Deserialize( EffectConfigDefine ins, System.IO.Stream stream )
        {
            tabtoy.DataReader reader = new tabtoy.DataReader(stream);
            if (!reader.ReadHeader())
            {
                throw new System.Exception(string.Format("Deserialize failed: {0}", ins.GetType()));
            }
            Deserialize(ins, reader);
        }
		static tabtoy.DeserializeHandler<EffectConfigDefine> _EffectConfigDefineDeserializeHandler;
		static tabtoy.DeserializeHandler<EffectConfigDefine> EffectConfigDefineDeserializeHandler
		{
			get
			{
				if (_EffectConfigDefineDeserializeHandler == null )
				{
					_EffectConfigDefineDeserializeHandler = new tabtoy.DeserializeHandler<EffectConfigDefine>(Deserialize);
				}

				return _EffectConfigDefineDeserializeHandler;
			}
		}
		public static void Deserialize( EffectConfigDefine ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x10000:
                	{
						ins.ID = reader.ReadInt32();
                	}
                	break; 
                	case 0x60001:
                	{
						ins.Path = reader.ReadString();
                	}
                	break; 
                	case 0x50002:
                	{
						ins.Time = reader.ReadFloat();
                	}
                	break; 
                }
             } 

			
		}
		#endregion
	

	} 

	// Defined in table: EffectConfigDefine
	[System.Serializable]
	public partial class EffectConfigDefine : tabtoy._BaseConfig
	{
	
		
		/// <summary> 
		/// 唯一ID（索引加MakeIndex:true）
		/// </summary>
		public int ID = 0; 
		
		/// <summary> 
		/// 路径
		/// </summary>
		public string Path = ""; 
		
		/// <summary> 
		/// 时长（单位秒）
		/// </summary>
		public float Time = 0f; 
	
	

	} 

}
