-- Generated By protoc-gen-lua Do not Edit
local protobuf = require('protobuf/protobuf')


local LOGINDATA = protobuf.Descriptor();
local LOGINDATA_USER_FIELD = protobuf.FieldDescriptor();
local LOGINDATA_PASS_FIELD = protobuf.FieldDescriptor();

LOGINDATA_USER_FIELD.name = "user"
LOGINDATA_USER_FIELD.full_name = ".Nas.WorldProto.LoginData.user"
LOGINDATA_USER_FIELD.number = 1
LOGINDATA_USER_FIELD.index = 0
LOGINDATA_USER_FIELD.label = 1
LOGINDATA_USER_FIELD.has_default_value = false
LOGINDATA_USER_FIELD.default_value = ""
LOGINDATA_USER_FIELD.type = 9
LOGINDATA_USER_FIELD.cpp_type = 9

LOGINDATA_PASS_FIELD.name = "pass"
LOGINDATA_PASS_FIELD.full_name = ".Nas.WorldProto.LoginData.pass"
LOGINDATA_PASS_FIELD.number = 2
LOGINDATA_PASS_FIELD.index = 1
LOGINDATA_PASS_FIELD.label = 1
LOGINDATA_PASS_FIELD.has_default_value = false
LOGINDATA_PASS_FIELD.default_value = ""
LOGINDATA_PASS_FIELD.type = 9
LOGINDATA_PASS_FIELD.cpp_type = 9

LOGINDATA.name = "LoginData"
LOGINDATA.full_name = ".Nas.WorldProto.LoginData"
LOGINDATA.nested_types = {}
LOGINDATA.enum_types = {}
LOGINDATA.fields = {LOGINDATA_USER_FIELD, LOGINDATA_PASS_FIELD}
LOGINDATA.is_extendable = false
LOGINDATA.extensions = {}

local LoginData = protobuf.Message(LOGINDATA)

return LoginData