-- Generated By protoc-gen-lua Do not Edit
local protobuf = require('protobuf/protobuf')
local Position_pb = require('pb/Position_pb')


local MONSTERDATA = protobuf.Descriptor();
local MONSTERDATA_MONSTERID_FIELD = protobuf.FieldDescriptor();
local MONSTERDATA_POS_FIELD = protobuf.FieldDescriptor();
local MONSTERDATA_MONSTERTYPE_FIELD = protobuf.FieldDescriptor();

MONSTERDATA_MONSTERID_FIELD.name = "monsterId"
MONSTERDATA_MONSTERID_FIELD.full_name = ".Nas.WorldProto.MonsterData.monsterId"
MONSTERDATA_MONSTERID_FIELD.number = 1
MONSTERDATA_MONSTERID_FIELD.index = 0
MONSTERDATA_MONSTERID_FIELD.label = 1
MONSTERDATA_MONSTERID_FIELD.has_default_value = false
MONSTERDATA_MONSTERID_FIELD.default_value = ""
MONSTERDATA_MONSTERID_FIELD.type = 9
MONSTERDATA_MONSTERID_FIELD.cpp_type = 9

MONSTERDATA_POS_FIELD.name = "pos"
MONSTERDATA_POS_FIELD.full_name = ".Nas.WorldProto.MonsterData.pos"
MONSTERDATA_POS_FIELD.number = 2
MONSTERDATA_POS_FIELD.index = 1
MONSTERDATA_POS_FIELD.label = 1
MONSTERDATA_POS_FIELD.has_default_value = false
MONSTERDATA_POS_FIELD.default_value = nil
MONSTERDATA_POS_FIELD.message_type = Position_pb.POSITION
MONSTERDATA_POS_FIELD.type = 11
MONSTERDATA_POS_FIELD.cpp_type = 10

MONSTERDATA_MONSTERTYPE_FIELD.name = "monsterType"
MONSTERDATA_MONSTERTYPE_FIELD.full_name = ".Nas.WorldProto.MonsterData.monsterType"
MONSTERDATA_MONSTERTYPE_FIELD.number = 3
MONSTERDATA_MONSTERTYPE_FIELD.index = 2
MONSTERDATA_MONSTERTYPE_FIELD.label = 1
MONSTERDATA_MONSTERTYPE_FIELD.has_default_value = false
MONSTERDATA_MONSTERTYPE_FIELD.default_value = ""
MONSTERDATA_MONSTERTYPE_FIELD.type = 9
MONSTERDATA_MONSTERTYPE_FIELD.cpp_type = 9

MONSTERDATA.name = "MonsterData"
MONSTERDATA.full_name = ".Nas.WorldProto.MonsterData"
MONSTERDATA.nested_types = {}
MONSTERDATA.enum_types = {}
MONSTERDATA.fields = {MONSTERDATA_MONSTERID_FIELD, MONSTERDATA_POS_FIELD, MONSTERDATA_MONSTERTYPE_FIELD}
MONSTERDATA.is_extendable = false
MONSTERDATA.extensions = {}

local MonsterData = protobuf.Message(MONSTERDATA)

return MonsterData