-- Generated By protoc-gen-lua Do not Edit
local protobuf = require('protobuf/protobuf')
local Position_pb = require('pb/Position_pb')


local PLAYERUPDATEDATA = protobuf.Descriptor();
local PLAYERUPDATEDATA_POSITION_FIELD = protobuf.FieldDescriptor();

PLAYERUPDATEDATA_POSITION_FIELD.name = "position"
PLAYERUPDATEDATA_POSITION_FIELD.full_name = ".Nas.WorldProto.PlayerUpdateData.position"
PLAYERUPDATEDATA_POSITION_FIELD.number = 1
PLAYERUPDATEDATA_POSITION_FIELD.index = 0
PLAYERUPDATEDATA_POSITION_FIELD.label = 1
PLAYERUPDATEDATA_POSITION_FIELD.has_default_value = false
PLAYERUPDATEDATA_POSITION_FIELD.default_value = nil
PLAYERUPDATEDATA_POSITION_FIELD.message_type = Position_pb.POSITION
PLAYERUPDATEDATA_POSITION_FIELD.type = 11
PLAYERUPDATEDATA_POSITION_FIELD.cpp_type = 10

PLAYERUPDATEDATA.name = "PlayerUpdateData"
PLAYERUPDATEDATA.full_name = ".Nas.WorldProto.PlayerUpdateData"
PLAYERUPDATEDATA.nested_types = {}
PLAYERUPDATEDATA.enum_types = {}
PLAYERUPDATEDATA.fields = {PLAYERUPDATEDATA_POSITION_FIELD}
PLAYERUPDATEDATA.is_extendable = false
PLAYERUPDATEDATA.extensions = {}

local PlayerUpdateData = protobuf.Message(PLAYERUPDATEDATA)

return PlayerUpdateData