-- Generated By protoc-gen-lua Do not Edit
local protobuf = require('protobuf/protobuf')


local PLAYERID = protobuf.Descriptor();
local PLAYERID_ID_FIELD = protobuf.FieldDescriptor();

PLAYERID_ID_FIELD.name = "id"
PLAYERID_ID_FIELD.full_name = ".Nas.WorldProto.PlayerId.id"
PLAYERID_ID_FIELD.number = 1
PLAYERID_ID_FIELD.index = 0
PLAYERID_ID_FIELD.label = 1
PLAYERID_ID_FIELD.has_default_value = false
PLAYERID_ID_FIELD.default_value = ""
PLAYERID_ID_FIELD.type = 9
PLAYERID_ID_FIELD.cpp_type = 9

PLAYERID.name = "PlayerId"
PLAYERID.full_name = ".Nas.WorldProto.PlayerId"
PLAYERID.nested_types = {}
PLAYERID.enum_types = {}
PLAYERID.fields = {PLAYERID_ID_FIELD}
PLAYERID.is_extendable = false
PLAYERID.extensions = {}

local PlayerId = protobuf.Message(PLAYERID)

return PlayerId