-- DO NOT EDIT
-- Generated by Exporter
-- Version: 2.8.11
BasisAnimConfig = {}

BasisAnimConfig.datas = 
{
	{ ID = 304000001, Type = 0, Ctrl = "monani_00_001", Idle = "monani_00_001_sta01", Run = "monani_00_001_run01", BattleBefore = "", BattleIdle = "monani_00_001_sta01", BattleAfter = "", BattleRun = "monani_00_001_run01", SpecialIdle = "", SpecialRun = "", Hurt = "monani_00_001_hurt01", Repel = "", Roll = "", Dead = "monani_00_001_dead01" 	},
	{ ID = 304000002, Type = 0, Ctrl = "monani_00_002", Idle = "monani_00_002_sta01", Run = "monani_00_002_run01", BattleBefore = "", BattleIdle = "monani_00_002_sta01", BattleAfter = "", BattleRun = "monani_00_002_run01", SpecialIdle = "", SpecialRun = "", Hurt = "monani_00_002_hurt01", Repel = "", Roll = "", Dead = "monani_00_002_dead01" 	},
	{ ID = 304000003, Type = 0, Ctrl = "monani_00_003", Idle = "monani_00_003_sta01", Run = "monani_00_003_run01", BattleBefore = "", BattleIdle = "monani_00_003_sta01", BattleAfter = "", BattleRun = "monani_00_003_run01", SpecialIdle = "", SpecialRun = "", Hurt = "monani_00_003_hurt01", Repel = "", Roll = "", Dead = "monani_00_003_dead01" 	},
	{ ID = 304000004, Type = 0, Ctrl = "monani_00_004", Idle = "monani_00_004_sta01", Run = "monani_00_004_run01", BattleBefore = "", BattleIdle = "monani_00_004_sta01", BattleAfter = "", BattleRun = "monani_00_004_run01", SpecialIdle = "", SpecialRun = "", Hurt = "monani_00_004_hurt01", Repel = "", Roll = "", Dead = "monani_00_004_dead01" 	},
	{ ID = 304000005, Type = 0, Ctrl = "monani_00_005", Idle = "monani_00_005_sta01", Run = "monani_00_005_run01", BattleBefore = "", BattleIdle = "monani_00_005_sta01", BattleAfter = "", BattleRun = "monani_00_005_run01", SpecialIdle = "", SpecialRun = "", Hurt = "monani_00_005_hurt01", Repel = "", Roll = "", Dead = "monani_00_005_dead01" 	},
	{ ID = 304000006, Type = 0, Ctrl = "monani_00_006", Idle = "monani_00_006_sta01", Run = "monani_00_006_run01", BattleBefore = "", BattleIdle = "monani_00_006_sta01", BattleAfter = "", BattleRun = "monani_00_006_run01", SpecialIdle = "", SpecialRun = "", Hurt = "monani_00_006_hurt01", Repel = "", Roll = "", Dead = "monani_00_006_dead01" 	},
	{ ID = 304000007, Type = 0, Ctrl = "monani_00_007", Idle = "monani_00_007_sta01", Run = "monani_00_007_run01", BattleBefore = "", BattleIdle = "monani_00_007_sta01", BattleAfter = "", BattleRun = "monani_00_007_run01", SpecialIdle = "", SpecialRun = "", Hurt = "monani_00_007_hurt01", Repel = "", Roll = "", Dead = "monani_00_007_dead01" 	},
	{ ID = 304000008, Type = 0, Ctrl = "monani_01_001", Idle = "monani_01_001_sta01", Run = "monani_01_001_run01", BattleBefore = "", BattleIdle = "monani_01_001_sta01", BattleAfter = "", BattleRun = "monani_01_001_run01", SpecialIdle = "", SpecialRun = "", Hurt = "monani_01_001_hurt01", Repel = "", Roll = "", Dead = "monani_01_001_dead01" 	},
	{ ID = 304000009, Type = 0, Ctrl = "monani_01_002", Idle = "monani_01_002_sta01", Run = "monani_01_002_run01", BattleBefore = "", BattleIdle = "monani_01_002_sta01", BattleAfter = "", BattleRun = "monani_01_002_run01", SpecialIdle = "", SpecialRun = "", Hurt = "monani_01_002_hurt01", Repel = "", Roll = "", Dead = "monani_01_002_dead01" 	},
	{ ID = 304000010, Type = 0, Ctrl = "monani_01_003", Idle = "monani_01_003_sta01", Run = "monani_01_003_run01", BattleBefore = "", BattleIdle = "monani_01_003_sta01", BattleAfter = "", BattleRun = "monani_01_003_run01", SpecialIdle = "", SpecialRun = "", Hurt = "monani_01_003_hurt01", Repel = "", Roll = "", Dead = "monani_01_003_dead01" 	},
	{ ID = 304000011, Type = 0, Ctrl = "monani_02_001", Idle = "monani_02_001_sta01", Run = "monani_02_001_run01", BattleBefore = "", BattleIdle = "monani_02_001_sta01", BattleAfter = "", BattleRun = "monani_02_001_run01", SpecialIdle = "", SpecialRun = "", Hurt = "monani_02_001_hurt01", Repel = "", Roll = "", Dead = "monani_02_001_dead01" 	},
	{ ID = 304000012, Type = 0, Ctrl = "monani_02_002", Idle = "monani_02_002_sta01", Run = "monani_02_002_run01", BattleBefore = "", BattleIdle = "monani_02_002_sta01", BattleAfter = "", BattleRun = "monani_02_002_run01", SpecialIdle = "", SpecialRun = "", Hurt = "monani_02_002_hurt01", Repel = "", Roll = "", Dead = "monani_02_002_dead01" 	},
	{ ID = 304010001, Type = 1, Ctrl = "ani_01", Idle = "ani_01_025f", Run = "ani_01_026f", BattleBefore = "ani_01_011f", BattleIdle = "ani_01_001f", BattleAfter = "ani_01_012f", BattleRun = "ani_01_003f", SpecialIdle = "ani_01_002f", SpecialRun = "ani_01_004f", Hurt = "ani_01_007f", Repel = "ani_01_009f", Roll = "ani_01_008f", Dead = "ani_01_010f" 	},
	{ ID = 304010002, Type = 2, Ctrl = "ani_01", Idle = "ani_01_025m", Run = "ani_01_026m", BattleBefore = "ani_01_011m", BattleIdle = "ani_01_001m", BattleAfter = "ani_01_012m", BattleRun = "ani_01_003m", SpecialIdle = "ani_01_002m", SpecialRun = "ani_01_004m", Hurt = "ani_01_007m", Repel = "ani_01_009m", Roll = "ani_01_008m", Dead = "ani_01_010m" 	},
	{ ID = 304030001, Type = 1, Ctrl = "ani_03", Idle = "ani_03_019f", Run = "ani_03_020f", BattleBefore = "ani_03_009f", BattleIdle = "ani_03_001f", BattleAfter = "ani_03_010f", BattleRun = "ani_03_002f", SpecialIdle = "", SpecialRun = "", Hurt = "ani_03_005f", Repel = "ani_03_007f", Roll = "ani_03_006f", Dead = "ani_03_008f" 	},
	{ ID = 304030002, Type = 2, Ctrl = "ani_03", Idle = "ani_03_019m", Run = "ani_03_020m", BattleBefore = "ani_03_009m", BattleIdle = "ani_03_001m", BattleAfter = "ani_03_010m", BattleRun = "ani_03_002m", SpecialIdle = "", SpecialRun = "", Hurt = "ani_03_005m", Repel = "ani_03_007m", Roll = "ani_03_006m", Dead = "ani_03_008m" 	}
}


-- ID
BasisAnimConfig._datas = {}
for _, rec in pairs(BasisAnimConfig.datas) do
	BasisAnimConfig._datas[rec.ID] = rec
end

function BasisAnimConfig.getByID(ID)
	return BasisAnimConfig._datas[ID]
end
