// Generated by tabtoy
// Version: 2.8.11
// DO NOT EDIT!!
using System.Collections.Generic;

namespace NasData
{
	
	

	// Defined in table: OpenGameModule
	
	public partial class OpenGameModule : tabtoy._BaseConfig
	{
	
		public tabtoy.Logger TableLogger = new tabtoy.Logger();
	
		
		/// <summary> 
		/// OpenGameModule
		/// </summary>
		public List<OpenGameModuleDefine> Datas = new List<OpenGameModuleDefine>(); 
	
	
		#region Index code
	 	Dictionary<string, OpenGameModuleDefine> _ByID = new Dictionary<string, OpenGameModuleDefine>();
        public OpenGameModuleDefine GetByID(string ID, OpenGameModuleDefine def = default(OpenGameModuleDefine))
        {
            OpenGameModuleDefine ret;
            if ( _ByID.TryGetValue( ID, out ret ) )
            {
                return ret;
            }
			
			if ( def == default(OpenGameModuleDefine) )
			{
				TableLogger.ErrorLine("GetByID failed, ID: {0}", ID);
			}

            return def;
        }
		
	
		#endregion
		#region Deserialize code
		public override void Deserialize(System.IO.Stream stream)
        {
            Deserialize(this, stream);
        }
		
		public static void Deserialize( OpenGameModule ins, System.IO.Stream stream )
        {
            tabtoy.DataReader reader = new tabtoy.DataReader(stream);
            if (!reader.ReadHeader())
            {
                throw new System.Exception(string.Format("Deserialize failed: {0}", ins.GetType()));
            }
            Deserialize(ins, reader);
        }
		static tabtoy.DeserializeHandler<OpenGameModule> _OpenGameModuleDeserializeHandler;
		static tabtoy.DeserializeHandler<OpenGameModule> OpenGameModuleDeserializeHandler
		{
			get
			{
				if (_OpenGameModuleDeserializeHandler == null )
				{
					_OpenGameModuleDeserializeHandler = new tabtoy.DeserializeHandler<OpenGameModule>(Deserialize);
				}

				return _OpenGameModuleDeserializeHandler;
			}
		}
		public static void Deserialize( OpenGameModule ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0xa0000:
                	{
						ins.Datas.Add( reader.ReadStruct<OpenGameModuleDefine>(OpenGameModuleDefineDeserializeHandler) );
                	}
                	break; 
                }
             } 

			
			// Build OpenGameModule Index
			for( int i = 0;i< ins.Datas.Count;i++)
			{
				var element = ins.Datas[i];
				
				ins._ByID.Add(element.ID, element);
				
			}
			
		}
		public static void Deserialize( OpenGameModuleDefine ins, System.IO.Stream stream )
        {
            tabtoy.DataReader reader = new tabtoy.DataReader(stream);
            if (!reader.ReadHeader())
            {
                throw new System.Exception(string.Format("Deserialize failed: {0}", ins.GetType()));
            }
            Deserialize(ins, reader);
        }
		static tabtoy.DeserializeHandler<OpenGameModuleDefine> _OpenGameModuleDefineDeserializeHandler;
		static tabtoy.DeserializeHandler<OpenGameModuleDefine> OpenGameModuleDefineDeserializeHandler
		{
			get
			{
				if (_OpenGameModuleDefineDeserializeHandler == null )
				{
					_OpenGameModuleDefineDeserializeHandler = new tabtoy.DeserializeHandler<OpenGameModuleDefine>(Deserialize);
				}

				return _OpenGameModuleDefineDeserializeHandler;
			}
		}
		public static void Deserialize( OpenGameModuleDefine ins, tabtoy.DataReader reader )
		{
			
 			int tag = -1;
            while ( -1 != (tag = reader.ReadTag()))
            {
                switch (tag)
                { 
                	case 0x60000:
                	{
						ins.ID = reader.ReadString();
                	}
                	break; 
                	case 0x60001:
                	{
						ins.name = reader.ReadString();
                	}
                	break; 
                	case 0x10002:
                	{
						ins.openLevel = reader.ReadInt32();
                	}
                	break; 
                	case 0x10003:
                	{
						ins.eventId = reader.ReadInt32();
                	}
                	break; 
                	case 0x60004:
                	{
						ins.icon = reader.ReadString();
                	}
                	break; 
                }
             } 

			
		}
		#endregion
	

	} 

	// Defined in table: OpenGameModuleDefine
	[System.Serializable]
	public partial class OpenGameModuleDefine : tabtoy._BaseConfig
	{
	
		
		/// <summary> 
		/// 唯一ID（索引加MakeIndex:true）
		/// </summary>
		public string ID = ""; 
		
		/// <summary> 
		/// 系统名
		/// </summary>
		public string name = ""; 
		
		/// <summary> 
		/// 开放等级
		/// </summary>
		public int openLevel = 0; 
		
		/// <summary> 
		/// 开启事件
		/// </summary>
		public int eventId = 0; 
		
		/// <summary> 
		/// 系统图标
		/// </summary>
		public string icon = ""; 
	
	

	} 

}
