-- DO NOT EDIT
-- Generated by Exporter
-- Version: 2.8.11
OpenGameModule = {}

local _datas = 
{
	{ ID = "1", name = "角色系统", openLevel = 1, eventId = 0, icon = "9010001" 	},
	{ ID = "2", name = "背包系统", openLevel = 1, eventId = 0, icon = "9010002" 	},
	{ ID = "3", name = "技能系统", openLevel = 1, eventId = 6010001, icon = "9010003" 	}
}


-- ID
OpenGameModule.datas = {}
for _, rec in pairs(_datas) do
	OpenGameModule.datas[rec.ID] = rec
end

function OpenGameModule.getByID(ID)
	return OpenGameModule.datas[ID]
end
