-- DO NOT EDIT
-- Generated by Exporter
-- Version: 2.8.11
FunctionOpenConfig = {}

FunctionOpenConfig.datas = 
{
	{ ID = "1", Name = "角色系统", OpenType = 0, OpenLevel = 1, EventId = 0, Icon = { "juesefenye1", "juesefenye22" }, OpenBoot = 0, ModuleName = "ActorInfoPanel" 	},
	{ ID = "2", Name = "背包系统", OpenType = 0, OpenLevel = 1, EventId = 0, Icon = { "beibaofenye1", "beibaofenye22" }, OpenBoot = 0, ModuleName = "BagPanel" 	},
	{ ID = "3", Name = "技能系统", OpenType = 0, OpenLevel = 1, EventId = 0, Icon = { "jineng", "Word-Skill" }, OpenBoot = 0, ModuleName = "SkillPanel" 	},
	{ ID = "4", Name = "宝典系统", OpenType = 0, OpenLevel = 1, EventId = 0, Icon = { "baodian", "Word-Treasure" }, OpenBoot = 0, ModuleName = "" 	},
	{ ID = "5", Name = "生活系统", OpenType = 0, OpenLevel = 1, EventId = 0, Icon = { "shenghuo", "Word-Life" }, OpenBoot = 0, ModuleName = "" 	},
	{ ID = "6", Name = "拍卖行系统", OpenType = 0, OpenLevel = 1, EventId = 0, Icon = { "paimaihang", "Word-AuctionHouse" }, OpenBoot = 0, ModuleName = "" 	},
	{ ID = "7", Name = "排行榜系统", OpenType = 0, OpenLevel = 1, EventId = 0, Icon = { "paixingbang", "Word-RankingList" }, OpenBoot = 0, ModuleName = "" 	},
	{ ID = "8", Name = "佣兵团系统", OpenType = 0, OpenLevel = 1, EventId = 0, Icon = { "yongbingtuan", "Word-Mercenary" }, OpenBoot = 0, ModuleName = "" 	},
	{ ID = "9", Name = "设置系统", OpenType = 0, OpenLevel = 1, EventId = 0, Icon = { "shezhi", "Word-SetUp" }, OpenBoot = 0, ModuleName = "" 	}
}


-- ID
FunctionOpenConfig._datas = {}
for _, rec in pairs(FunctionOpenConfig.datas) do
	FunctionOpenConfig._datas[rec.ID] = rec
end

function FunctionOpenConfig.getByID(ID)
	return FunctionOpenConfig._datas[ID]
end
