-- DO NOT EDIT
-- Generated by Exporter
-- Version: 2.8.11
SkillAnimConfig = {}

SkillAnimConfig.datas = 
{
	{ ID = 30401001, Type = 1, Ctrl = "ani_01", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_013f_skill02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401002, Type = 1, Ctrl = "ani_01", ActionID = "skill2", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_014f_skill03", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401003, Type = 1, Ctrl = "ani_01", ActionID = "skill3", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_014f_skill04", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401004, Type = 1, Ctrl = "ani_01", ActionID = "skill4", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_013f_skill05", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401005, Type = 1, Ctrl = "ani_01", ActionID = "skill5", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_013f_skill06", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401006, Type = 1, Ctrl = "ani_01", ActionID = "skill6", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_018f_skill07", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401007, Type = 1, Ctrl = "ani_01", ActionID = "skill7", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "", LastingEnter = "ani_01_019f_skill08_01", Lasting = "ani_01_019f_skill08_02", LastingExit = "ani_01_019f_skill08_03" 	},
	{ ID = 30401008, Type = 1, Ctrl = "ani_01", ActionID = "skill8", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "ani_01_020f_skill09_01", Instant = "ani_01_020f_skill09_02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401009, Type = 1, Ctrl = "ani_01", ActionID = "skill9", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_021f_skill10", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401010, Type = 1, Ctrl = "ani_01", ActionID = "skill10", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "", LastingEnter = "ani_01_022f_skill11_01", Lasting = "ani_01_022f_skill11_02", LastingExit = "ani_01_022f_skill11_03" 	},
	{ ID = 30401011, Type = 1, Ctrl = "ani_01", ActionID = "skill11", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_023f_skill12", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401012, Type = 1, Ctrl = "ani_01", ActionID = "skill12", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_024f_skill13", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401013, Type = 2, Ctrl = "ani_01", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_013m_skill02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401014, Type = 2, Ctrl = "ani_01", ActionID = "skill2", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_014m_skill03", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401015, Type = 2, Ctrl = "ani_01", ActionID = "skill3", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_014m_skill04", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401016, Type = 2, Ctrl = "ani_01", ActionID = "skill4", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_013m_skill05", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401017, Type = 2, Ctrl = "ani_01", ActionID = "skill5", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_013m_skill06", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401018, Type = 2, Ctrl = "ani_01", ActionID = "skill6", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_018m_skill07", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401019, Type = 2, Ctrl = "ani_01", ActionID = "skill7", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "", LastingEnter = "ani_01_019m_skill08_01", Lasting = "ani_01_019m_skill08_02", LastingExit = "ani_01_019m_skill08_03" 	},
	{ ID = 30401020, Type = 2, Ctrl = "ani_01", ActionID = "skill8", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "ani_01_020m_skill09_01", Instant = "ani_01_020m_skill09_02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401021, Type = 2, Ctrl = "ani_01", ActionID = "skill9", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_021m_skill10", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401022, Type = 2, Ctrl = "ani_01", ActionID = "skill10", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "", LastingEnter = "ani_01_022m_skill11_01", Lasting = "ani_01_022m_skill11_02", LastingExit = "ani_01_022m_skill11_03" 	},
	{ ID = 30401023, Type = 2, Ctrl = "ani_01", ActionID = "skill11", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_023m_skill12", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401024, Type = 2, Ctrl = "ani_01", ActionID = "skill12", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_024m_skill13", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401025, Type = 1, Ctrl = "ani_01", ActionID = "melee", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_005f_attack01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401026, Type = 1, Ctrl = "ani_01", ActionID = "melee", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_006f_attack02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401027, Type = 2, Ctrl = "ani_01", ActionID = "melee", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_005m_attack01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30401028, Type = 2, Ctrl = "ani_01", ActionID = "melee", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_01_006m_attack02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403001, Type = 1, Ctrl = "ani_03", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_011f_skill02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403002, Type = 1, Ctrl = "ani_03", ActionID = "skill2", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_012f_skill03", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403003, Type = 1, Ctrl = "ani_03", ActionID = "skill3", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_013f_skill04", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403004, Type = 1, Ctrl = "ani_03", ActionID = "skill4", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_014f_skill05", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403005, Type = 1, Ctrl = "ani_03", ActionID = "skill5", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_015f_skill06", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403006, Type = 1, Ctrl = "ani_03", ActionID = "skill6", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_016f_skill07", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403007, Type = 1, Ctrl = "ani_03", ActionID = "skill7", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "ani_03_017f_skill08_01", Instant = "ani_03_017f_skill08_02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403008, Type = 1, Ctrl = "ani_03", ActionID = "skill8", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_015f_skill09", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403009, Type = 1, Ctrl = "ani_03", ActionID = "skill9", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_015f_skill10", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403010, Type = 1, Ctrl = "ani_03", ActionID = "skill10", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_015f_skill11", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403011, Type = 1, Ctrl = "ani_03", ActionID = "skill11", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_015f_skill12", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403012, Type = 1, Ctrl = "ani_03", ActionID = "skill12", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_018f_skill13", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403013, Type = 2, Ctrl = "ani_03", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_011m_skill02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403014, Type = 2, Ctrl = "ani_03", ActionID = "skill2", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_012m_skill03", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403015, Type = 2, Ctrl = "ani_03", ActionID = "skill3", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_013m_skill04", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403016, Type = 2, Ctrl = "ani_03", ActionID = "skill4", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_014m_skill05", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403017, Type = 2, Ctrl = "ani_03", ActionID = "skill5", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_015m_skill06", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403018, Type = 2, Ctrl = "ani_03", ActionID = "skill6", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_016m_skill07", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403019, Type = 2, Ctrl = "ani_03", ActionID = "skill7", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "ani_03_017m_skill08_01", Instant = "ani_03_017m_skill08_02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403020, Type = 2, Ctrl = "ani_03", ActionID = "skill8", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_015m_skill09", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403021, Type = 2, Ctrl = "ani_03", ActionID = "skill9", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_015m_skill10", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403022, Type = 2, Ctrl = "ani_03", ActionID = "skill10", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_015m_skill11", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403023, Type = 2, Ctrl = "ani_03", ActionID = "skill11", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_015m_skill12", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403024, Type = 2, Ctrl = "ani_03", ActionID = "skill12", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_018m_skill13", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400001, Type = 0, Ctrl = "monani_00_001", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_00_001_atk01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403027, Type = 1, Ctrl = "ani_03", ActionID = "melee", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_003m_attack01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403028, Type = 1, Ctrl = "ani_03", ActionID = "melee", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_004m_attack02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403029, Type = 2, Ctrl = "ani_03", ActionID = "melee", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_003f_attack01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30403030, Type = 2, Ctrl = "ani_03", ActionID = "melee", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "ani_03_004f_attack02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400002, Type = 0, Ctrl = "monani_00_004", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_00_004_atk01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400003, Type = 0, Ctrl = "monani_00_002", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_00_002_atk01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400004, Type = 0, Ctrl = "monani_00_003", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_00_003_atk01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400005, Type = 0, Ctrl = "monani_00_005", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_00_005_atk01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400006, Type = 0, Ctrl = "monani_00_006", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_00_006_atk01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400007, Type = 0, Ctrl = "monani_00_007", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_00_007_atk01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400008, Type = 0, Ctrl = "monani_01_001", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_01_001_atk01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400009, Type = 0, Ctrl = "monani_01_001", ActionID = "skill2", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_01_001_atk02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400010, Type = 0, Ctrl = "monani_01_002", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_01_002_atk01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400011, Type = 0, Ctrl = "monani_01_002", ActionID = "skill2", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_01_002_atk02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400012, Type = 0, Ctrl = "monani_01_003", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_01_003_atk01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400013, Type = 0, Ctrl = "monani_01_003", ActionID = "skill2", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_01_003_atk02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400014, Type = 0, Ctrl = "monani_02_001", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_02_001_atk01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400015, Type = 0, Ctrl = "monani_02_001", ActionID = "skill2", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_02_001_atk02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400016, Type = 0, Ctrl = "monani_02_002", ActionID = "skill1", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_02_002_atk01", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400017, Type = 0, Ctrl = "monani_02_002", ActionID = "skill2", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_02_002_atk02", LastingEnter = "", Lasting = "", LastingExit = "" 	},
	{ ID = 30400018, Type = 0, Ctrl = "monani_02_002", ActionID = "skill3", CastingEnter = "", Casting = "", CastingExit = "", InstantEnter = "", Instant = "monani_02_002_atk03", LastingEnter = "", Lasting = "", LastingExit = "" 	}
}


-- ID
SkillAnimConfig._datas = {}
for _, rec in pairs(SkillAnimConfig.datas) do
	SkillAnimConfig._datas[rec.ID] = rec
end

function SkillAnimConfig.getByID(ID)
	return SkillAnimConfig._datas[ID]
end
