-- DO NOT EDIT
-- Generated by Exporter
-- Version: 2.8.11
FixedRuleList = {}

local _datas = 
{
	{ ID = "1", ParamType = 1, Value = 30 	},
	{ ID = "2", ParamType = 2, Value = 30 	},
	{ ID = "3", ParamType = 3, Value = 10 	},
	{ ID = "3", ParamType = 3, Value = 10 	}
}


-- ID
FixedRuleList.datas = {}
for _, rec in pairs(_datas) do
	FixedRuleList.datas[rec.ID] = rec
end

function FixedRuleList.getByID(ID)
	return FixedRuleList.datas[ID]
end
